---

- hosts: appservers
  remote_user: ansible
  become: yes
  roles:
    - java-1.8
    - tomcat

- hosts: webservers
  remote_user: ansible
  become: yes
  roles:
    - httpd

- hosts: dbservers
  remote_user: ansible
  become: yes
  roles:
    - mysql

- hosts: appservers
  remote_user: ansible
  become: yes
  roles:
    - crud_deploy
  tags:
    - crud
